### ISSUE TITLE
MacOS color is kinda off

### ISSUE THREAD

**Issue by haunt98** [Dr-Noob/cpufetch#129]
The apple ascii art color in `cpufetch` is kinda off, compare to `neofetch`

![image](https://user-images.githubusercontent.com/5424272/141683586-b6a0e48a-6b58-451c-9088-93af0b5dbb9c.png)

![image](https://user-images.githubusercontent.com/5424272/141683601-3f81f725-7896-4cd6-b919-7da390e12354.png)

**Comment by Dr-Noob** [comment]
I prefer the logo color to be as close as possible to the real one, instead of having the logo colored like neofetch. I know that the logo color in neofetch was actually the official logo in some moment of the history of Apple, but right now it is not. 

That said, I agree that the current color scheme is not very elegant in terminals with a black background. Any suggestions to improve it? I may change that in the future, and use brighter colors for the text too.

**Comment by haunt98** [comment]
I agree with you that current Apple logo is OK. But name text (`SOC`, `Technology`) should use brighter colors for terminal with dark colorschemes

**Comment by Dr-Noob** [comment]
I do not know a reliable way to fetch the color scheme of the terminal so if I change any color it will be for all terminals. But yes, I will make the text brighter (probably bright blue or something along the lines).

**Comment by Dr-Noob** [comment]
Hey, I've changed the color.

Can you try again (download the code again) and paste the output to see how it looks now?

**Comment by haunt98** [comment]
I use the latest source to try again. It is looking good right now! Thank you!
![image](https://user-images.githubusercontent.com/5424272/144704136-8ed52b16-579f-40d7-acb5-1a9b4b3cf562.png)
