### ISSUE TITLE
OpenSUSE package

### ISSUE THREAD

**Issue by WoMspace** [Dr-Noob/cpufetch#144]
Please add OpenSUSE builds.
A reminder that the [OBS](https://openbuildservice.org/) exists and can be used to automate builds for pretty much every distribution.

**Comment by Dr-Noob** [comment]
I'm the developer, not a package maintainer. I just maintain the Arch Linux package since it's my daily driver, but for any other distro, I think you should look somewhere else. 

In fact, I don't know much about OpenSUSE. I guess that [this](https://snapcraft.io/install/cpufetch/opensuse) might be enough? 

In any case, if you want an OpenSUSE package, I'm not the one you are looking for, you should try asking OpenSUSE package maintainers.

**Comment by WoMspace** [comment]
Ah ok! Thanks for the reply
