### ISSUE TITLE
[ARM][Android]Kirin960 not being detected correctly

### ISSUE THREAD

**Issue by QQxiaoming** [Dr-Noob/cpufetch#157]
Hi Dr, it's me again.😁

I have an old Android device Kirin960 from Honor 9. I just tried cpufetch out of curiosity. like this：

![Screenshot_20220921_235949_com cpuid cpu_z](https://user-images.githubusercontent.com/27486515/191557900-4fc2b8d0-4ec3-4013-8eee-199cee7f3626.jpg)

So I installed termux, and built cpufetch. got this:

![Screenshot_20220921_234213_com termux](https://user-images.githubusercontent.com/27486515/191558330-7ed6a950-e89a-4c7f-a701-7e86975d6a97.jpg)

I looked into it, maybe change "Hi" and "Hi3660" inside match_hisilicon to "hi" and "hi3660" and then I'll get this:

![Screenshot_20220921_234345_com termux](https://user-images.githubusercontent.com/27486515/191560266-1b892397-e66b-4ccc-b51a-01cbf6d7cfb6.jpg)

The end, sorry I'm not a native English speaker, maybe my expression is not very good.

**Comment by Dr-Noob** [comment]
Hey, thanks for the report.

This is the first time I ever see cpufetch running in a Kirin SoC since I added support for it (which was around two years ago :sweat_smile:). Looks like SoC names are reported with "hi" instead of "Hi" - I updated the master branch with that change, can you confirm it works as expected?

**Comment by QQxiaoming** [comment]
Awesome, it works as expected now.
