### ISSUE TITLE
Error: Found invalid cpu_family: 0x00000000 (macOS 13 arm64)

### ISSUE THREAD

**Issue by p-linnane** [Dr-Noob/cpufetch#163]
Hello. I am a maintainer for [Homebrew](https://brew.sh) project. While attempting to package `cpufetch` for the arm64 version of macOS Ventura, we are encountering a test failure.

```
==> Testing cpufetch
  ==> /opt/homebrew/Cellar/cpufetch/1.02/bin/cpufetch -d
  [ERROR]: Found invalid cpu_family: 0x00000000
  Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
```

The full GitHub Actions run can be found [here](https://github.com/Homebrew/homebrew-core/actions/runs/3678662930/jobs/6222193005). This job was run on a 2020 Mac mini with an M1 chip.

**Comment by Dr-Noob** [comment]
I don't know how you built the binary, but that error probably means that the build process was not run on an ARM Apple chip. Please note that the program will only work for ARM/Apple if it was built in such an environment. 

If you believe it was built inside the right environment, I suggest downloading and compiling manually, like in [the README](https://github.com/Dr-Noob/cpufetch#22-building-from-source). If you build it following those instructions and you encounter the same problem, then it is a problem of cpufetch itself and I should investigate further - otherwise is a problem with your setup.

**Comment by p-linnane** [comment]
The job was run on a macOS Ventura VM running on a 2020 Mac mini with an M1 chip. The program builds fine, we are just running `make` as described in the README. FWIW, this is only happening on the arm64 version of macOS Ventura. We have no issues on 2 other arm64 and 4 other Intel versions of macOS.

**Comment by Dr-Noob** [comment]
cpufetch uses [sysctlbyname](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/sysctlbyname.3.html) to query cpu_family in ARM/macOS, which is the function failing in this case. It is not clear what is the problem - whether it's because of the latest macOS version or because it is running in a VM (VMs typically affect this kind of function) in the latest macOS version.

I would suggest copying the generated executable to a non-vm macOS Ventura and checking if it still fails.

**Comment by p-linnane** [comment]
I can confirm building locally on my machine returned the expected results. I will need to do some more research into why that particular version of macOS is having issues when virtualized. Thank you.

**Comment by Dr-Noob** [comment]
Thanks.

If you find something relevant I would appreciate it if you could post it here so I can warn future users about that to avoid confusion.
