### ISSUE TITLE
OnePlus 10T - Android 13

### ISSUE THREAD

**Issue by lmservas** [Dr-Noob/cpufetch#177]
I received the following errors running cpufetch on my OnePlus 10T:

![Screenshot_2023-03-27-14-52-07-25_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/33529347/228075686-edc7fccb-3330-48d4-b083-79483a30fc61.jpg)
![Screenshot_2023-03-27-14-52-18-20_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/33529347/228075695-5b8e4f1a-86c7-4658-b890-20cc5cd20aa8.jpg)

**Comment by Dr-Noob** [comment]
This was fixed in issue #170, but you are using the cpufetch v1.03 release (probably the one from termux). To get the last patches, you need to download and build from source, as explained in the [README](https://github.com/Dr-Noob/cpufetch#23-android). Feel free to reopen the issue if you build it from source and still does not work.

**Comment by lmservas** [comment]
Your absolutely right I was using the Termux package. I apologize for missing this. Thanks!!
