### ISSUE TITLE
Support for Transmeta Crusoe CPU

### ISSUE THREAD

**Issue by danielinux** [Dr-Noob/cpufetch#239]
This would require a third `CPU_VENDOR` in the x86 family. Check PR #238 for more details.

**Comment by timw4mail** [comment]
There are quite a few interesting (but minor) x86 vendors. 

I would also appreciate more x86 vendors. `Centaur` (VIA) and` Zhaoxin` come to mind first, as these are the most modern. 

There's also Cyrix, Rise, and I think UMC has a 486 chip with cpuinfo support. (And the first generation of Centaur chips under the IDT Winchip name). 

While it would be a fun exercise to add them all, I would at least like to see Centaur and Transmeta (since that seems to work).

I do have hardware for these vendors I mentioned, as well.

**Comment by Dr-Noob** [comment]
> This would require a third `CPU_VENDOR` in the x86 family. Check PR #238 for more details.

Sorry for the delay and thank you for your contribution! I have reopened the PR and left a quick review which should be a good starting point. I'm more than happy to accept it if we end up with a clean, working implementation for Transmeta :+1:

**Comment by Dr-Noob** [comment]
> Centaur



> There are quite a few interesting (but minor) x86 vendors.
> 
> I would also appreciate more x86 vendors. `Centaur (CentaurHauls)` under IDT, VIA. and Zhaoxin brands, comes to mind first, as these are the most modern.
> 
> For 32 bit chips of the Pentium era, there's also `Cyrix (CyrixInstead)`, `Rise (RiseRiseRise)`, and `UMC (UMC UMC UMC )` has a 486 chip with cpuinfo support.
> 
> While it would be a fun exercise to add them all, I would at least like to see Centaur and Transmeta (since that seems to work).
> 
> I do have hardware for these vendors I mentioned, as well.

I obviously do not have that hardware to add support for it, but if you have, I would be open to review a PR to add support for Centaur.

**Comment by Dr-Noob** [comment]
Closing this issue, let's continue the conversation in #238.
