### ISSUE TITLE
Information for several AArch64 SoCs

### ISSUE THREAD

**Issue by hrw** [Dr-Noob/cpufetch#276]
Please take a look at https://github.com/hrw/arm-socs-table repo. You have information for several Arm SoCs there. Feel free to use (MIT licensed).

Also /proc/cpuinfo dumps if you prefer.

**Comment by Dr-Noob** [comment]
Thanks for the reference, I'll keep that in mind!  

I don't see how that helps improving [get_uarch_from_midr](https://github.com/Dr-Noob/cpufetch/blob/master/src/arm/uarch.c#L161) or the SoC information [here](https://github.com/Dr-Noob/cpufetch/blob/master/src/arm/soc.c) though. It seems like your repo has significantly less data than cpufetch. If you find anything that I could incorporate from your repo please let me know :+1:

**Comment by hrw** [comment]
All parts you take from midr are in YAML files.

Cpu_cores one lists cores with implementer while SoCs one lists all so a with info which cores are present in which variant, revision.

You still have to check system details but would have list of existing cpu cores and SoCs where they are used.

**Comment by Dr-Noob** [comment]
I still don't understand how that improves what I have. To be more precise:

- Microarchitecture: You say "_Cpu_cores one lists cores with implementer_". Okay, [here](https://github.com/hrw/arm-socs-table/blob/main/data/cpu_cores.yml) you have a list of microarchitectures, yes. But I don't see any that I don't have already [here](https://github.com/Dr-Noob/cpufetch/blob/master/src/arm/uarch.c#L161). I would need to run an automatic tool to find out if there is any which does not seem to be the most efficient way to invest my time right now.
- SoCs: Same, [here](https://github.com/hrw/arm-socs-table/blob/main/data/socs.yml) you have a list of SoCs. I think there is a misunderstanding here. From what I understand, you have a list of SoCs and its CPU cores, whereas I need to uniquely identify a SoC, which is implemented by getting the SoC from `/proc/cpuinfo` or (recently added) `/proc/device-tree/compatible`. The latter is yet to be finished and thus might give users the impression that cpufetch has a lot of missing SoCs, which is true, but this list does not help me in any way, since I need `cpuinfo` or `device-tree` values to uniquely identify a SoC.

Please let me know if my understanding is incorrect or if there is any other way I can benefit from your work. Thanks for your time :+1:

**Comment by hrw** [comment]
On Arm you should check two places:

- /sys/firmware/devicetree/base/{compatible,model} (if they are present)
- dmidecode data (if they are present)

Cause some systems boot with DeviceTree, some use ACPI. In both cases some data (like topology) can be completely bogus - amount of cpu cores will match but sockets/clusters/cores/threads may not.
