### ISSUE TITLE
[ERROR]: Can't read frequency information from cpuid

### ISSUE THREAD

**Issue by Sommerbo** [Dr-Noob/cpufetch#52]
[ERROR]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x0000000D)
[ERROR]: Found unified cache at level 4 (expected == 2 or 3)
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues

I gather the first error is a known issue but I couldn't find anything on the second one.

CPU: Crystal Well Core i7 2.8GHz  
It is an MSI Laptop if that matters, please tell what else you need to debug this issue.

For fun I tried cpufetch in PS, cmd and WSL2 debian all returned the same errors (both), so at least the code is consistent.

lscpu from WSL2 Debian
oscar@MSI-Laptop:~$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 70
Model name:            Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
Stepping:              1
CPU MHz:               2801.000
CPU max MHz:           2801.0000
BogoMIPS:              5602.00
Virtualization:        VT-x
Hypervisor vendor:     Windows Subsystem for Linux
Virtualization type:   container
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid ibrs ibpb stibp ssbd

**Comment by Dr-Noob** [comment]
Hi, thanks for your post,

The second error, as you said, has been already reported an will be fixed soon.

The first error is impossible to fix. If your CPU does not support to fetch the frequency, `cpufetch`can't do anything about that. However, in Linux, `cpufetch` will report the frecuency correctly, since it will ask the frequency to the kernel instead of asking the CPU itself. I should change the verbosity of the error to avoid a bunch of useless issues in the future.

I don't know how WSL works, but if you can run a native Linux application, try `cpufetch` compiled for Linux inside it. If not, close the issue, since there are not issues to be fixed (that have not been posted elsewhere).

Thanks!

**Comment by Sommerbo** [comment]
Using WSL2 to compile and run cpufetch is something I did for fun. It probably should be considered an edge case.
