### ISSUE TITLE
src/arm/midr.c:8:10: fatal error: asm/hwcap.h: No such file or directory  #include <asm/hwcap.h>

### ISSUE THREAD

**Issue by dank-foss** [Dr-Noob/cpufetch#53]
sujeet@sujeet-pc:~/MyStuff/cpufetch$ make
gcc -Wall -Wextra -Werror -pedantic -fstack-protector-all -pedantic -std=c99 -DARCH_ARM -Wno-unused-parameter -Wfloat-equal -Wshadow -Wpointer-arith src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/arm/midr.c src/arm/uarch.c src/arm/soc.c src/arm/udev.c -o cpufetch
src/arm/midr.c:8:10: fatal error: asm/hwcap.h: No such file or directory
 #include <asm/hwcap.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:45: cpufetch] Error 1
how do I deal with this

**Comment by Dr-Noob** [comment]
Hi,

Please, specify a bit of information about your environment. What operating system are you using? Version?

**Comment by dank-foss** [comment]
this is on Debian 10 buster i686, will send the lscpu in a while, can't right now

**Comment by Dr-Noob** [comment]
@dank-foss You should do a `git pull` since I updated the Makefile to work with i686 CPUs
@avollmerhaus Great to see that someone is trying on a POWER9. Unfortunately, `cpufetch` does not support that architecture, as we discussed in the other issue. Yes, it is assuming that it is ARM when it's not, I will change the Makefile to fix that issue.

**Comment by Dr-Noob** [comment]
Closing the issue because it didn't receive any messages after a long time. 

i686 should work with the new Makefile, ppc64le will probably be added in the future.
