### ISSUE TITLE
Wrong Processor info on Samsung Galaxy M51

### ISSUE THREAD

**Issue by sriansu** [Dr-Noob/cpufetch#54]
The mentioned phone has a Snapdragon 730G processor but the output shows a SD 675 and a completely different architecture.

![photo_2021-04-07_15-45-33](https://user-images.githubusercontent.com/58145425/113850887-8bca4e00-97b8-11eb-8e94-38aef46a6f6c.jpg)
![photo_2021-04-07_15-48-44](https://user-images.githubusercontent.com/58145425/113851107-c59b5480-97b8-11eb-86ee-f13b2a328301.jpg)

**Comment by Dr-Noob** [comment]
Hi,

Good to see an Android issue. But from what I can see from your pictures, it doesn't look  very well. 😅

I would need some extra information to understand what's happening;

- The output of `cpufetch --verbose` and `cpufetch --debug`
- The contents of the file `/proc/cpuinfo`

Thanks!

**Comment by sriansu** [comment]
> Hi,
> 
> Good to see an Android issue. But from what I can see from your pictures, it doesn't look very well. 
> 
> I would need some extra information to understand what's happening;
> 
> * The output of `cpufetch --verbose` and `cpufetch --debug`
> * The contents of the file `/proc/cpuinfo`
> 
> Thanks!

I see what's the reason of the output. Here are the attached files.
![verbose](https://user-images.githubusercontent.com/58145425/113857731-7fe28a00-97c0-11eb-8aa8-b5b8d2060c19.jpg)
[debug.txt](https://github.com/Dr-Noob/cpufetch/files/6271127/debug.txt)
[cpuinfo.txt](https://github.com/Dr-Noob/cpufetch/files/6271130/cpuinfo.txt)

**Comment by Dr-Noob** [comment]
Alright, so there are esentially two bugs here:

- **The SoC**. I don't know why but I have found some Snapdragon CPUs that provide wrong data. In your case, Android says that your CPU is a Snapdragon 675 (maybe because the ROM you have installed is not the official one? I don't know), while Linux kernel itself says it is a Snapdragon 730 (actually, it says `SDMMAGPIE`, but I can translate this name into the SoC model). I have created a new branch called `bugfix3`. Please, try the new commit I have pushed and let me know if the SoC is detected correctly or not.
- **The microarchitecture**. As reported by CPU-Z, it must be Kyro 470. This is a known bug in cpufetch, tracked in issue #34. It's a bit tricky to detect the exact Kyro version from the CPU itself, but I will work on this when I get some free time (I hardly believe that CPU-Z knows that it is a Kyro 470 just because the SoC is a SnapD 730, so it assumes that all SnapD 730 have Kyro 470, which should be true, but `cpufetch` is not designed to work like this, which is essentially a database).

Thank you very much for your help!

**Comment by sriansu** [comment]
> Alright, so there are esentially two bugs here:
> 
> * **The SoC**. I don't know why but I have found some Snapdragon CPUs that provide wrong data. In your case, Android says that your CPU is a Snapdragon 675 (maybe because the ROM you have installed is not the official one? I don't know), while Linux kernel itself says it is a Snapdragon 730 (actually, it says `SDMMAGPIE`, but I can translate this name into the SoC model). I have created a new branch called `bugfix3`. Please, try the new commit I have pushed and let me know if the SoC is detected correctly or not.
> * **The microarchitecture**. As reported by CPU-Z, it must be Kyro 470. This is a known bug in cpufetch, tracked in issue #34. It's a bit tricky to detect the exact Kyro version from the CPU itself, but I will work on this when I get some free time (I hardly believe that CPU-Z knows that it is a Kyro 470 just because the SoC is a SnapD 730, so it assumes that all SnapD 730 have Kyro 470, which should be true, but `cpufetch` is not designed to work like this, which is essentially a database).
> 
> Thank you very much for your help!

It is the official ROM. But, I will definitely checkout bugfix3.  Thank you for the response.
