### ISSUE TITLE
32Bit compiling?

### ISSUE THREAD

**Issue by JPRuehmann** [Dr-Noob/cpufetch#55]
Is there a Way to compile cpufetch in 32Bit Linux?
I am using Kubuntu 18.04 LTS (32Bit)
Thanks,

**Comment by Dr-Noob** [comment]
Hi, thank you for your question.

I have never had the opportunity to run `cpufetch` in a 32 bit (x86) CPU. But because you seem to have one, let's try how it goes!

I have created a new branch called `i686` and created a new commit which should let you at least build `cpufetch` for 32 bit. Give it a try and let's see what happens.

**Comment by JPRuehmann** [comment]
Thanks, works like a charm.
