### ISSUE TITLE
Add more architectures

### ISSUE THREAD

**Issue by erkinalp** [Dr-Noob/cpufetch#59]
Add support for MIPS, SPARC and RISC-V.

**Comment by Dr-Noob** [comment]
Hi, thanks for your idea.

I'm not sure if you are aware or not but each architecture would probably need months of development.

It's a good future project, but I will only consider it if I have access to some real CPUs that implement those architectures. I'm particularly interested in RISC-V. Do you have access to any of these architectures?

**Comment by erkinalp** [comment]
I have MIPS STBs but never tried Linux on them.

RISC-V has a commercially available motherboard&SoC by SiFive, but never had a chance to try one.

**Comment by avollmerhaus** [comment]
I've got a ppc64le ready to go and could maybe contribute ia64 and sparc64 if I am able to get the machines running again...

**Comment by avollmerhaus** [comment]
Blocked by https://github.com/Dr-Noob/cpufetch/issues/59 on the ppc64le machine.

**Comment by Dr-Noob** [comment]
Hi guys, sorry for your interest.

I'm sorry, but unless things change dramatically, I will not support any of these architectures.

If RISC-V becomes more popular in the future, it might be added, but the rest of them are very scarce and I don't have access to any of them (and don't think I will ever have). Furthermore, if a few people benefit from such enhancement, I would not be interested because it would add a lot of complexity to the source code for so little benefit.

**Comment by avollmerhaus** [comment]
ia64 and Sparc64 are mostly dead I guess. But at least ppc64le might be more popular than assumed, although it's dwarfed by ARM or x86(64) of course. But there is a popular brand of libre workstations (Raptor Computing's TalosII) using ppc64le and people still build clusters from the IBM machines as well.
I'd especially love to see cpufetch running on my Talos and would be willing to help with testing and debugging (but have no particular C skills of my own).

**Comment by Dr-Noob** [comment]
Yeah, `ppc64le` might be interesting, specially because it looks like it has some powerful CPUs. But without access to the hardware I can't do much. If you know any way to have free access to this kind of machine, or if you can give me temporary ssh access to yours, I might consider adding this architecture to `cpufetch` 🤔

**Comment by avollmerhaus** [comment]
They sure are, I'm regularly compiling Firefox, LibreOffice and much more on mine, it's the fastest machine I have.
Power9 machines also currently occupy the second and third places on the top 500 supercomputer list.
(While that is surely also due to their of their GPUs, it still shows how capable the architecture is)

Would a KVM-based VM suffice for your needs?

**Comment by Dr-Noob** [comment]
I'm afraid not. 

From my experience working with x86_64, VMs can fake a lot of information about the CPU. For example, the number of cores, frequency, and probably other kinds of stuff. If I decide to dive into the world of powerpc to add support in `cpufetch` it has to be a non-virtual machine. Testing on VMs can be interesting, but this would be after the development is done, to test if it still works on VMs.

FYI, I'm used to work on Linux-based machines through ssh. I've had ssh access to one supercomputer in the Top 500 list last year and I'm the admin of two different HPC clusters in the institution where I work (which in fact helps a lot to debug and test `cpufetch` in many different CPUs).

**Comment by avollmerhaus** [comment]
Okay, I'm in the process of preparing my TalosII with a temporary HDD and a fresh Fedora33 installation for you to access.
Is there a private communication channel that we could use to coordinate SSH access?
I'm on Telegram, but we could also use IRC via Freenode or plain old email.

Haha, okay, brilliant, and here I am lecturing you about supercomputers.
Now I feel stupid!

**Comment by Dr-Noob** [comment]
That's sounds great!

Send me an e-mail and I will forward you my Telegram username.

PS: You can find my e-mail in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cpufetch-git

**Comment by avollmerhaus** [comment]
Email is out! :)

**Comment by Dr-Noob** [comment]
Closing the issue.

POWER9/PowerPC support will probably be added in the near future.
