### ISSUE TITLE
Outdated Intel Logo

### ISSUE THREAD

**Issue by christgau** [Dr-Noob/cpufetch#63]
The Intel logo/brand has changed last year: https://www.intel.com/content/www/us/en/company-overview/visual-brand-identity.html, https://www.theverge.com/2020/9/2/21418540/intel-new-logo-2020-redesign-minimalist-branding. The ASCII art in cpufetch still uses the swirl logo... although I like that one. Nevertheless, I am unable to judge on copyright/brand usage issues here.

**Comment by Dr-Noob** [comment]
Hi, thanks for your suggestion.

Yeah, I know that Intel changed the logo and I was thinking about adding the new one as a extra option. Something like `./cpufetch --new-intel-logo`. For the moment I'm not going to add this, but may be added in the future.

By the way, have a look at the `ascii` branch. You will be surprised. I have not publicized too much that feature since I'm not sure what I'm going to do with it, since not all terminal supports it...

**Comment by Dr-Noob** [comment]
So I had this idea in the things to do in the future and finally, I had time to work on this. 

You will find the new Intel logo in the master branch. By default, the new logo only will appear if you have an Intel CPU that was released after Intel started using the new logo. If not, the normal logo will appear. However, you can also change this behavior using `--logo-intel-new` which will always show the new one. You can also print the smaller logo version with `--logo-short`. Personally, I would recommend running it like: `./cpufetch  --logo-intel-new --color intel-new`. Any advice on the new logo are welcomed!
