### ISSUE TITLE
Improvement: Needs way more than 80 chars Terminal width && doesn't cut text after width

### ISSUE THREAD

**Issue by Noxmiles** [Dr-Noob/cpufetch#65]
With an Intel i3-6100U it needs 121 characters Terminal width to show everything without newlines.

neofetch is measuring the width and cutting the text after this width. cpufetch writes everything, so the logo is disrupted in almost every line.

Screenshot of a terminal with a width of 80:
![image](https://user-images.githubusercontent.com/10343510/114018498-9692ea80-986d-11eb-9b3a-254df41410d6.png)

**Comment by Dr-Noob** [comment]
Hi,

Thanks for your suggestion. I like your idea. I will leave this issue opened and I may work on this in the future.

However, bear in mind that neofetch can "easily" track the width of the terminal because is written in bash and is aimed to work only on Linux terminals (I guess...), but `cpufetch` works on lots of different OS (and thus terminals) and is written in C. In the case of `cpufetch` it will probably be harder, but I could get it to work.

**Comment by Dr-Noob** [comment]
I have implemented a first version of this idea in `feat` branch. Give it a try and let me know what do you think about it.

In the case of `cpufetch` is a bit harder to fit everything because the Intel logo is wider than most of distribution logos...

**Comment by Dr-Noob** [comment]
Already in master branch. The current version of cpufetch should fit seamlessly in an 80-width terminal, even without cutting the text. If the full output is wider than the terminal width, the text will be cut. Closing.
