### ISSUE TITLE
Publish to scoop

### ISSUE THREAD

**Issue by Milo123459** [Dr-Noob/cpufetch#72]
Publish the package to [scoop](https://scoop.sh)
[Here is the main bucket](https://github.com/scoopinstaller/main)

**Comment by Dr-Noob** [comment]
Hi,

I didn't know about scoop, but I like the idea. I guess that I have to do a PR with the .json to install `cpufetch`? I will work on that whenever I get some free time.

Thanks!

**Comment by Milo123459** [comment]
Yes, but I can do it for you, you just have to make sure that the release name for the executable always is the same.

**Comment by Milo123459** [comment]
@Dr-Noob For the "bin" section, should it be cpufetch.exe?

**Comment by Milo123459** [comment]
[Here](https://github.com/ScoopInstaller/Main/pull/2065), I created a PR

**Comment by Dr-Noob** [comment]
Hi,

Thanks for your help. It's a bit of a pain in the ass to keep updating the URL (since the next versions of `cpufetch` will need a different one), but for compiled binaries I guess that it is the best we can do.

If they finally accept the PR, I will encourage you to do a PR to `cpufetch` too to upload the .json so you appear as a contributor (I would appreciate if you could update the .json whenever I release new Windows versions).

PS: I would like to do the same for `brew` (https://github.com/Homebrew/brew), but I don't how it works? Do you?

**Comment by Milo123459** [comment]
I'm familiar with brew so I can helpout!

**Comment by Dr-Noob** [comment]
Great! Let me know if you need anything to make `cpufetch` a `brew` package. 

If you end up doing it, I think it's a good idea to do another PR to include it in the `cpufetch` repository, and keep all of them in the same place. And I would proably add the arch package too.

**Comment by Dr-Noob** [comment]
Looks like [this](https://github.com/Dr-Noob/cpufetch/issues/95) is more appropiate than scoop and it seems that there is not much interest in this issue because of the lack of activity. Closing.
