### ISSUE TITLE
Error building on Windows

### ISSUE THREAD

**Issue by patevs** [Dr-Noob/cpufetch#77]
On Windows 10 I get the following error when attempting to build from source.

```cmd
src/common/printer.c: In function 'set_ascii':
src/common/printer.c:235:47: error: 'ENABLE_VIRTUAL_TERMINAL_PROCESSING' undeclared (first use in this function)
     SetConsoleMode(std_handle, console_mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Dr-Noob** [comment]
Hi, thank you for reporting this error.

That's interesting...so it looks like in "old" Windows, that flag is not defined. Please, have a look at the commit in `bugfix` branch. Try it out, it should build successfully, and let me know if the output of `cpufetch` is colored or not (I assume it will be not, probably because the Windows version does not support it).

**Comment by patevs** [comment]
`bugfix` branch builds successfully and the output is colored.

**Comment by Dr-Noob** [comment]
Nice! Thanks for the report.

Closing the issue and merging to master branch.
