### ISSUE TITLE
[ERROR]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x0000000D)

### ISSUE THREAD

**Issue by patevs** [Dr-Noob/cpufetch#78]
Running the current Windows release (v0.94) gives the following error:

```
[ERROR]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x0000000D)
```

CPU information is display correctly except:

```
Max Frequency:     Unknown
Peak Performance:  Unknown
```

**Comment by Dr-Noob** [comment]
Hi, thanks for your message.

This is not a error in `cpufetch` in itself. I changed the error message in newer versions of `cpufetch`, since I can't do anything to solve it. The message means that `cpufetch` tried reading the frequency of your CPU from  the CPU itself but your CPU does not  support it (quite often in AMD). Therefore, frequency is not displayed and neither peak performance, because is computed using the frequency.

In linux you will get the frequency even tough your CPU does not support it via cpuid, because `cpufetch` will ask Linux the frequency, but in Windows this is not possible.

I will update the binaries for Windows. Closing.
