### ISSUE TITLE
Socket count wrong

### ISSUE THREAD

**Issue by zid** [Dr-Noob/cpufetch#96]
https://cdn.discordapp.com/attachments/417023075348119556/868523060481912852/unknown.png

My E5-1620 shows with:

Sockets: 4

It's a uniprocessor machine, not quad socket.

This also makes it look like I have an impressive 40MB of L3 instead of 10MB.

**Comment by Dr-Noob** [comment]
Virtual machines (VMware in this case) can tamper the CPU values as they want, so VMware can report that your CPU has 4 sockets when it is not true. This cannot be considered a bug in cpufetch itself, unless you run the program in a bare metal OS (no VM) and you get the same (wrong) results. The wrong L3 size is also because the wrong socket count.

If you can test cpufetch in the machine directly, please give it a try. If not, just close this issue because there is no issue at all. Thanks!

**Comment by zid** [comment]
Yea the KVM can mess with it, I still think multiplying the cache size by the socket count is super bizzare though.

**Comment by Dr-Noob** [comment]
Each socket contains an invidiual CPU chip, which has its own L3 cache. So the total L3 cache is computed as the L3 of a single CPU multiplied by the number of CPUs (sockets). This is assuming that all the CPUs are the same (which is what cpufetch assumes).
